[[pages]]
path = "DashBoard.py"
name = "å®æ—¶æ¦‚è§ˆ"
icon = ":material/view_quilt:"

[[pages]]
name = "æ•°æ®ç®¡ç†"
icon = "ğŸ“–"
is_section = true

[[pages]]
path = "DetectedData.py"
name = "ç›‘æµ‹æ•°æ®"
icon = ":material/table_chart:"

[[pages]]
path = "Monitor_Info.py"
name = "è®¾å¤‡çŠ¶æ€"
icon = ":material/insert_chart_outlined:"

[[pages]]
name = "æ•°æ®åˆ†æåŠŸèƒ½"
icon = "ğŸ“œ"
is_section = true

[[pages]]
path = "Alert.py"
name = "é¢„è­¦å’Œå»ºè®®"
icon = ":material/notification_important:"
[[pages]]
path = "Predict.py"
name = "é¢„æµ‹"
icon = ":material/timeline:"
url_path = "a_very_long_page_title"
